Logistic Regression Implementation

In [10]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore")

In [12]:
df= pd.read_csv(r"C:\Users\ACER\OneDrive\Desktop\ML project\Implementation\tested.csv")
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
413,1305,0,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
414,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
415,1307,0,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,0,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
417,1309,0,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

In [13]:
print(df.shape)
print(df.columns)
df.head()

(418, 12)
Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  418 non-null    int64
 1   Survived     418 non-null    int64
 2   Pclass       418 non-null    int64
 3   Name         418 non-null    object
 4   Sex          418 non-null    object
 5   Age          332 non-null    float64
 6   SibSp        418 non-null    int64
 7   Parch        418 non-null    int64
 8   Ticket       418 non-null    object
 9   Fare         417 non-null    float64
 10  Cabin        91 non-null     object
 11  Embarked     418 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 39.3+ KB

In [15]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [16]:
df = df.drop(columns=["PassengerId", "Name", "Ticket", "Cabin"])

In [17]:
df.head()

   Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  34.5      0      0   7.8292        Q
1         1       3  female  47.0      1      0   7.0000        S
2         0       2    male  62.0      0      0   9.6875        Q
3         0       3    male  27.0      0      0   8.6625        S
4         1       3  female  22.0      1      1  12.2875        S

In [18]:
df["Age"] = df["Age"].fillna(
    df["Age"].median()
)

In [19]:
df["Fare"] = df["Fare"].fillna(
    df["Fare"].median()
)

In [20]:
df.isnull().sum()

Survived    0
Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        0
Embarked    0
dtype: int64

In [21]:
df["Sex"] = df["Sex"].map({
    "male": 0,
    "female": 1
})

In [22]:
df = pd.get_dummies(
    df,
    columns=["Embarked"],
    drop_first=True,
    dtype=int
)

In [23]:
df.head()

   Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked_Q  Embarked_S
0         0       3    0  34.5      0      0   7.8292           1           0
1         1       3    1  47.0      1      0   7.0000           0           1
2         0       2    0  62.0      0      0   9.6875           1           0
3         0       3    0  27.0      0      0   8.6625           0           1
4         1       3    1  22.0      1      1  12.2875           0           1

In [24]:
df.dtypes

Survived        int64
Pclass          int64
Sex             int64
Age           float64
SibSp           int64
Parch           int64
Fare          float64
Embarked_Q      int64
Embarked_S      int64
dtype: object

In [25]:
y = df["Survived"]

In [26]:
X = df.drop(columns=["Survived"])

In [27]:
print("X shape:", X.shape)
print("y shape:", y.shape)

X shape: (418, 8)
y shape: (418,)

In [28]:
X.head()

   Pclass  Sex   Age  SibSp  Parch     Fare  Embarked_Q  Embarked_S
0       3    0  34.5      0      0   7.8292           1           0
1       3    1  47.0      1      0   7.0000           0           1
2       2    0  62.0      0      0   9.6875           1           0
3       3    0  27.0      0      0   8.6625           0           1
4       3    1  22.0      1      1  12.2875           0           1

In [29]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size =0.2,
    random_state=42,
    stratify=y
)

In [30]:
print("X_train:", X_train.shape)
print("X_test :", X_test.shape)
print("y_train:", y_train.shape)
print("y_test :", y_test.shape)

X_train: (334, 8)
X_test : (84, 8)
y_train: (334,)
y_test : (84,)

In [31]:
from sklearn.linear_model import LogisticRegression

In [32]:
model=LogisticRegression(max_iter=1000)

In [33]:
model.fit(X_train,y_train)

LogisticRegression(max_iter=1000)

In [34]:
y_pred=model.predict(X_test)
print(y_pred)

[1 1 0 1 0 0 0 1 1 1 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 1 0 0 1
 0 0 0 0 1 1 1 0 0 0 0 0 0 0 1 1 1 0 1 1 0 0 0 1 1 0 0 1 1 0 1 1 1 0 0 1 0
 0 0 0 1 0 1 1 0 0 0]

In [35]:
y_prob = model.predict_proba(X_test)

print(y_prob[:5])

[[0.05140159 0.94859841]
 [0.04260378 0.95739622]
 [0.97735334 0.02264666]
 [0.05775124 0.94224876]
 [0.96502123 0.03497877]]

In [36]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

Accuracy: 1.0

In [37]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)

print(cm)

[[53  0]
 [ 0 31]]

In [38]:
from sklearn.metrics import precision_score, recall_score, f1_score

precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)

print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)

Precision: 1.0
Recall: 1.0
F1 Score: 1.0

KNN implementation

In [39]:
print(X.shape)
print(y.shape)

(418, 8)
(418,)

In [40]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("X_train:", X_train.shape)
print("X_test:", X_test.shape)
print("y_train:", y_train.shape)
print("y_test:", y_test.shape)

X_train: (334, 8)
X_test: (84, 8)
y_train: (334,)
y_test: (84,)

In [41]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [42]:
print(X_train_scaled[:5])

[[ 0.85435834 -0.75370758 -0.21477642 -0.48043064 -0.41184087 -0.50912957
  -0.33665016  0.70551956]
 [ 0.85435834 -0.75370758 -0.68236136 -0.48043064 -0.41184087 -0.49535877
  -0.33665016  0.70551956]
 [ 0.85435834 -0.75370758 -0.21477642 -0.48043064 -0.41184087 -0.49615131
   2.97044263 -1.41739515]
 [ 0.85435834 -0.75370758 -1.61753124 -0.48043064  0.6712682  -0.57539142
  -0.33665016  0.70551956]
 [ 0.85435834  1.3267745  -0.21477642 -0.48043064 -0.41184087 -0.49564602
   2.97044263 -1.41739515]]

Naive Bayes Implementation

In [43]:
from sklearn.neighbors import KNeighborsClassifier
model = KNeighborsClassifier(n_neighbors=5)

In [44]:
model.fit(X_train_scaled, y_train)

KNeighborsClassifier()

In [45]:
y_pred = model.predict(X_test_scaled)

print(y_pred)

[1 1 0 1 0 0 0 0 1 1 0 0 1 0 1 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 1 0 0 1
 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 1 1 0 1 1 0 0 0 1 1 0 0 1 1 0 1 1 1 0 0 1 0
 0 0 0 1 0 1 1 0 0 0]

In [46]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

Accuracy: 0.9642857142857143

In [47]:
from sklearn.naive_bayes import GaussianNB

model = GaussianNB()

model.fit(X_train, y_train)

GaussianNB()

In [48]:
y_pred_nb = model.predict(X_test_scaled)

print(y_pred_nb)

[1 1 0 1 0 0 0 1 1 1 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 1 0 0 1
 0 0 0 0 1 1 1 0 0 0 0 0 0 0 1 1 1 0 1 1 0 0 0 1 1 0 0 1 1 0 1 1 1 0 0 1 0
 0 0 0 1 0 1 1 0 0 0]

In [49]:
from sklearn.metrics import accuracy_score

accuracy_nb = accuracy_score(y_test, y_pred_nb)

print("Naive Bayes Accuracy:", accuracy_nb)

Naive Bayes Accuracy: 1.0

In [50]:
from sklearn.metrics import confusion_matrix

cm_nb = confusion_matrix(y_test, y_pred_nb)

print(cm_nb)

[[53  0]
 [ 0 31]]

In [51]:
from sklearn.metrics import precision_score, recall_score, f1_score

precision_nb = precision_score(y_test, y_pred_nb)
recall_nb = recall_score(y_test, y_pred_nb)
f1_nb = f1_score(y_test, y_pred_nb)

print("Precision:", precision_nb)
print("Recall:", recall_nb)
print("F1 Score:", f1_nb)

Precision: 1.0
Recall: 1.0
F1 Score: 1.0